(()=>{
const CARDSEL='.card,.match-card,.game-card';
const $=(r,s)=>r.querySelector(s), $$=(r,s)=>[...r.querySelectorAll(s)];
const text=e=>(e?.textContent||'').replace(/\s+/g,' ').trim();
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
const esc=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const palette={"bayern munchen":["#d71920","#0066b2"],"borussia dortmund":["#f2d400","#111111","#111"],"rb leipzig":["#e30613","#ffffff","#111"],"vfb stuttgart":["#e32219","#ffffff","#111"],"bayer leverkusen":["#e32219","#151515"],"eintracht frankfurt":["#e1000f","#171717"],"1. fc koln":["#e30613","#ffffff","#111"],"1. fsv mainz 05":["#d71920","#ffffff","#111"],"werder bremen":["#008c4a","#ffffff","#111"],"sc freiburg":["#d71920","#111111"],"paris saint-germain":["#163b75","#d7182a"],"borussia m'gladbach":["#111111","#ffffff","#111"],"kairat almaty":["#f3cf00","#111111","#111"],"levski sofia":["#1671d9","#ffffff","#111"]};
const state={view:'today',search:'',competition:'all',matches:[],dateControls:[],dateIndex:0,engine:null,app:null,refreshTimer:null,observer:null};
function colors(name){const k=norm(name);if(palette[k])return palette[k];let h=0;for(const c of k)h=(h*31+c.charCodeAt(0))%360;return[`hsl(${h} 68% 46%)`,`hsl(${(h+42)%360} 58% 27%)`]}
function initials(name){const p=(name||'').replace(/\b(fc|cf|sc|sv|fk|afc|club|de|the)\b/ig,'').trim().split(/\s+/).filter(Boolean);return(p.length>1?(p[0][0]||'')+(p[p.length-1][0]||''):(p[0]||'TV').slice(0,2)).toUpperCase()}
function markHTML(name){const[a,b,t]=colors(name);return`<span class="tvf-team-mark" style="--c1:${a};--c2:${b};${t?`--ct:${t};`:''}">${esc(initials(name))}</span>`}
function isFavControl(el){return el && (el.classList.contains('active')||el.classList.contains('on')||el.getAttribute('aria-pressed')==='true'||el.getAttribute('aria-checked')==='true'||el.checked===true)}
function uniqueTeams(card){const out=[];for(const el of $$(card,'.club,.team,.team-name')){const t=text(el);if(!t||t.length>70||/sender|stream|live|free-tv/i.test(t))continue;if(!out.some(x=>norm(x)===norm(t)))out.push(t);if(out.length===2)break}return out}
function comp(card){const e=$(card,'.competition,.comp,.league,.league-title,.meta');let t=text(e);if(!t){const all=text(card);const m=all.match(/(Champions League|Europa League|Conference League|Bundesliga|DFB.?Pokal|Premier League|LaLiga|Serie A|Ligue 1|2\. Bundesliga)/i);t=m?.[1]||'Fußball'}return t.slice(0,90)}
function score(card){for(const e of $$(card,'.score,.result,.match-score,.kickoff,.kick,.ko,.time')){const t=text(e);if(/^\d{1,2}:\d{2}$/.test(t))return{value:t,isTime:true};if(/^\d+\s*[:\-]\s*\d+$/.test(t))return{value:t.replace(/\s*[-:]\s*/, ' : '),isTime:false}}const m=text(card).match(/\b(\d{1,2}:\d{2})\b/);return{value:m?.[1]||'–',isTime:true}}
function live(card){return card.classList.contains('live')||card.classList.contains('tvf-is-live')||!!$(card,'.live,.live-badge,.live-status,[data-live="true"]')||/\bLIVE\b/.test(text(card).slice(0,180))}
function minute(card){const m=text(card).match(/\b(\d{1,3})(?:'|\.)/);return m?m[1]+"'":''}
function providers(card){const area=$(card,'.channels,.broadcast,.foot,.providers,.stations')||card;const out=[];for(const e of $$(area,'.ch,.channel,.provider,.station,.stream-link,a')){const t=text(e);if(!t||t.length>38||/mehr|detail|sender in|weitere länder|weitere sender|facebook|instagram/i.test(t))continue;if(out.some(x=>norm(x.text)===norm(t)))continue;out.push({text:t,href:e.tagName==='A'?e.href:'',free:/free|kostenlos|onefootball/i.test(t)});if(out.length===3)break}return out}
function ticker(card){const box=$(card,'.ticker,.live-ticker,.ticker-box,[data-ticker],#ticker');if(!box)return[];const rows=$$(box,'li,.ticker-row,.ticker-event,.event');return rows.slice(-8).map(r=>text(r)).filter(Boolean)}
function favControls(card){return $$(card,'.favorite,.fav,.star,[data-fav],[data-favorite]').filter(e=>!e.closest('.tvf-app')).slice(0,2)}
function parseMatches(){const candidates=$$(state.engine,CARDSEL);const seen=new Set, list=[];let id=0;for(const card of candidates){const teams=uniqueTeams(card);if(teams.length!==2)continue;const sc=score(card), key=teams.map(norm).join('|')+'|'+sc.value+'|'+comp(card);if(seen.has(key))continue;seen.add(key);const favs=favControls(card);list.push({id:'m'+(++id),source:card,home:teams[0],away:teams[1],competition:comp(card),score:sc.value,isTime:sc.isTime,live:live(card),minute:minute(card),providers:providers(card),ticker:ticker(card),favControls:favs,favHome:isFavControl(favs[0]),favAway:isFavControl(favs[1])})}state.matches=list;return list}
function resetEngineFilters(){const controls=$$(state.engine,'button,a,[role="button"],.tab,.btn,.m-btn');for(const el of controls){if(el.matches('.favorite,.fav,.star,[data-fav],[data-favorite]')||el.closest('.favorite,.fav,.star,[data-fav],[data-favorite]'))continue;const active=el.classList.contains('active')||el.classList.contains('on')||el.getAttribute('aria-pressed')==='true';if(!active)continue;const t=norm(text(el));if(/heute|today/.test(t))continue;if(/meine|favorit|bundesliga|champions|dfb|premier|laliga|la liga|deutschland|free|sender|land|wettbewerb/.test(t)){try{el.click()}catch{}}}for(const i of $$(state.engine,'input[type="search"],input[type="text"]')){if(i.value){i.value='';i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}))}}}
function collectDates(){const sels='.datebar button,.date-nav button,.dates button,.m-datebar button,.datebar a,.date-nav a,.dates a,.m-datebar a';let arr=$$(state.engine,sels);const unique=[];for(const e of arr){if(!unique.includes(e)&&text(e).length<40)unique.push(e);if(unique.length===7)break}state.dateControls=unique}
function cloneBrand(){const old=$(state.engine,'header .logo,.hdr .logo')||$(state.engine,'header a,.hdr a');if(old){const c=old.cloneNode(true);c.querySelectorAll('script').forEach(x=>x.remove());return c.outerHTML}return'<div class="tvf-brand-text"><span class="tvf-brand-box">TV</span>FUSSBALL.de</div>'}
function buildApp(){const root=document.createElement('div');root.id='tvf-app';root.className='tvf-app';root.innerHTML=`<header class="tvf-app-header"><div class="tvf-brand">${cloneBrand()}</div><nav class="tvf-topnav"><button class="active" data-view="today">Heute</button><button data-view="live">Live</button><button data-view="mine">Meine <span class="tvf-count">0</span></button><button data-view="highlights">Highlights</button></nav><div class="tvf-header-actions"><label class="tvf-search"><input type="search" placeholder="Suche (Team, Wettbewerb, Sender)" aria-label="Suche"></label><button class="tvf-theme" type="button" aria-label="Darstellung">☾</button></div></header><section class="tvf-hero"><div class="tvf-wrap"><div class="tvf-hero-copy"><div class="tvf-eyebrow">Fußball im TV & Stream</div><h1>Kein Spiel<br>mehr verpassen.</h1><p>Alle wichtigen Fußballspiele, Sender und Live-Updates auf einen Blick.</p><div class="tvf-stats"><div class="tvf-stat"><span class="tvf-stat-icon">⚽</span><div><strong data-stat="games">0</strong><span>Spiele heute</span></div></div><div class="tvf-stat"><span class="tvf-stat-icon">◉</span><div><strong data-stat="live">0</strong><span>Live</span></div></div><div class="tvf-stat"><span class="tvf-stat-icon">☆</span><div><strong data-stat="fav">0</strong><span>Favoriten</span></div></div></div></div><div class="tvf-datebar"></div><div class="tvf-chips"></div></div></section><main class="tvf-main"><div class="tvf-results"></div></main><nav class="tvf-mobile-nav"><button class="active" data-view="today">Heute</button><button data-view="live">Live</button><button data-view="mine">★ Meine</button><button data-view="highlights">Highlights</button></nav>`;document.body.insertBefore(root,state.engine);state.app=root;bindApp()}
function bindApp(){state.app.addEventListener('click',e=>{const view=e.target.closest('[data-view]');if(view){setView(view.dataset.view);return}const chip=e.target.closest('[data-comp]');if(chip){state.competition=chip.dataset.comp;render();return}const fav=e.target.closest('[data-fav-match]');if(fav){const m=state.matches.find(x=>x.id===fav.dataset.favMatch);const idx=Number(fav.dataset.team||0);const ctl=m?.favControls?.[idx];if(ctl){ctl.click();setTimeout(refresh,80)}return}const all=e.target.closest('[data-show-all]');if(all){setView(all.dataset.showAll);return}});const input=$(state.app,'.tvf-search input');input.addEventListener('input',()=>{state.search=input.value;render()});$(state.app,'.tvf-theme').addEventListener('click',()=>state.app.classList.toggle('tvf-low-contrast'))}
function setView(view){state.view=view;state.competition='all';$$(state.app,'[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render()}
function filtered(){let list=[...state.matches];if(state.view==='live')list=list.filter(m=>m.live);if(state.view==='mine')list=list.filter(m=>m.favHome||m.favAway);if(state.competition!=='all')list=list.filter(m=>norm(m.competition).includes(state.competition));const s=norm(state.search);if(s)list=list.filter(m=>norm([m.home,m.away,m.competition,...m.providers.map(p=>p.text)].join(' ')).includes(s));return list}
function teamHTML(name,m,idx){const active=idx===0?m.favHome:m.favAway;return`<div class="tvf-team">${markHTML(name)}<div class="tvf-team-name">${esc(name)} <button class="tvf-team-fav ${active?'active':''}" data-fav-match="${m.id}" data-team="${idx}" title="${active?'Favorit entfernen':'Als Favorit markieren'}">★</button></div></div>`}
function providerHTML(p){const tag=p.href?'a':'span';return`<${tag} class="tvf-provider ${p.free?'free':''}" ${p.href?`href="${esc(p.href)}" target="_blank" rel="noopener"`:''}>${esc(p.text)}</${tag}>`}
function liveCard(m){return`<article class="tvf-live-card"><div class="tvf-card-meta"><span class="tvf-live-badge">LIVE</span><span class="tvf-minute">${esc(m.minute||'LIVE')}</span></div><div class="tvf-card-match">${teamHTML(m.home,m,0)}<div class="tvf-score">${esc(m.score)}</div>${teamHTML(m.away,m,1)}</div><div class="tvf-card-foot">${m.providers.map(providerHTML).join('')}</div>${m.ticker.length?`<div class="tvf-ticker">${m.ticker.map(t=>`<div class="tvf-ticker-event">${esc(t)}</div>`).join('')}</div>`:''}</article>`}
function laterRow(m){return`<article class="tvf-later-row"><div class="tvf-later-time">${esc(m.score)}</div><div class="tvf-later-team">${markHTML(m.home)}<div class="tvf-team-name">${esc(m.home)} <button class="tvf-team-fav ${m.favHome?'active':''}" data-fav-match="${m.id}" data-team="0">★</button></div></div><div class="tvf-vs">vs.</div><div class="tvf-later-team">${markHTML(m.away)}<div class="tvf-team-name">${esc(m.away)} <button class="tvf-team-fav ${m.favAway?'active':''}" data-fav-match="${m.id}" data-team="1">★</button></div></div><div class="tvf-later-providers">${m.providers.map(providerHTML).join('')}</div></article>`}
function sectionHead(type,count){return`<div class="tvf-section-head ${type==='live'?'live':''}"><div class="tvf-section-title"><h2>${type==='live'?'Jetzt live':'Später heute'} <span>(${count})</span></h2></div><button data-show-all="${type==='live'?'live':'today'}">${type==='live'?'Alle Live-Spiele anzeigen':'Alle Spiele von heute anzeigen'} ›</button></div>`}
function renderHighlights(){const pool=$$(state.engine,'.highlight-card,.news-card,.analysis-card,.highlight,.analysis').slice(0,8);const cards=pool.map(el=>{const h=text($(el,'h1,h2,h3,strong'))||'Highlight';const p=text($(el,'p,.desc,.description'))||text(el).slice(h.length,220);return`<article class="tvf-highlight"><h3>${esc(h)}</h3><p>${esc(p.slice(0,260))}</p></article>`}).join('');return`<div class="tvf-section-head"><div class="tvf-section-title"><h2>Highlights</h2></div></div><div class="tvf-highlights">${cards||'<div class="tvf-empty">Aktuell sind keine Highlights verfügbar.</div>'}</div>`}
function render(){if(!state.app)return;renderDates();renderChips();const result=$(state.app,'.tvf-results');if(state.view==='highlights'){result.innerHTML=renderHighlights();updateStats();return}const list=filtered();const lives=list.filter(m=>m.live), later=list.filter(m=>!m.live);let html='';if(state.view!=='live'&&lives.length)html+=sectionHead('live',lives.length)+`<div class="tvf-live-grid">${lives.map(liveCard).join('')}</div>`;else if(state.view==='live')html+=sectionHead('live',lives.length)+`<div class="tvf-live-grid">${lives.map(liveCard).join('')}</div>`;if(state.view!=='live'&&later.length)html+=sectionHead('later',later.length)+`<div class="tvf-later-list">${later.map(laterRow).join('')}</div>`;if(!list.length)html='<div class="tvf-empty">Keine passenden Spiele gefunden.</div>';result.innerHTML=html;updateStats()}
function renderDates(){const bar=$(state.app,'.tvf-datebar');if(!bar)return;const fallback=['Heute','Mi.','Do.','Fr.','Sa.','So.','Mo.'];const labels=state.dateControls.length?state.dateControls.map(x=>text(x)):fallback;bar.innerHTML=labels.slice(0,7).map((label,i)=>{const parts=label.split(/\s+/);return`<button class="tvf-date ${i===state.dateIndex?'active':''}" data-date-index="${i}">${esc(parts[0]||fallback[i])}<small>${esc(parts.slice(1).join(' '))}</small></button>`}).join('')+'<div class="tvf-calendar">▣</div>';$$ (bar,'[data-date-index]').forEach(b=>b.addEventListener('click',()=>switchDate(Number(b.dataset.dateIndex))))}
function switchDate(i){const ctl=state.dateControls[i];state.dateIndex=i;if(ctl){try{ctl.click()}catch{}setTimeout(()=>{parseMatches();render()},180)}else render()}
function renderChips(){const box=$(state.app,'.tvf-chips');if(!box)return;const comps=[...new Set(state.matches.map(m=>m.competition).filter(Boolean))];const preferred=['Bundesliga','Champions League','DFB-Pokal','Premier League','LaLiga'];const shown=[];for(const p of preferred){const hit=comps.find(c=>norm(c).includes(norm(p)));if(hit)shown.push(hit)}for(const c of comps)if(!shown.includes(c)&&shown.length<5)shown.push(c);box.innerHTML=`<button class="tvf-chip ${state.competition==='all'?'active':''}" data-comp="all">Alle Wettbewerbe　⌄</button>${shown.map((c,i)=>`<button class="tvf-chip ${i<2?'star':'plus'} ${state.competition===norm(c)?'active':''}" data-comp="${esc(norm(c))}">${esc(c)}</button>`).join('')}<button class="tvf-chip more" type="button">☷　Mehr Filter</button>`}
function updateStats(){const favTeams=new Set;for(const m of state.matches){if(m.favHome)favTeams.add(norm(m.home));if(m.favAway)favTeams.add(norm(m.away))}const set=(k,v)=>{const e=$(state.app,`[data-stat="${k}"]`);if(e)e.textContent=v};set('games',state.matches.length);set('live',state.matches.filter(m=>m.live).length);set('fav',favTeams.size);$$(state.app,'.tvf-count').forEach(e=>e.textContent=favTeams.size)}
function refresh(){parseMatches();collectDates();render()}
function makeEngine(){const engine=document.createElement('div');engine.className='tvf-engine';engine.setAttribute('aria-hidden','true');const appScript=document.currentScript;const nodes=[...document.body.childNodes].filter(n=>n!==appScript);for(const n of nodes)engine.appendChild(n);document.body.appendChild(engine);state.engine=engine}
function observe(){let timer;state.observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(refresh,100)});state.observer.observe(state.engine,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['class','aria-pressed','aria-checked']})}
function boot(){makeEngine();resetEngineFilters();collectDates();parseMatches();buildApp();render();observe();setTimeout(refresh,350);setTimeout(refresh,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();