(()=>{
'use strict';
const $=(r,s)=>r&&r.querySelector?r.querySelector(s):null;
const $$=(r,s)=>r&&r.querySelectorAll?[...r.querySelectorAll(s)]:[];
const text=e=>(e?.textContent||'').replace(/\s+/g,' ').trim();
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
const esc=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const CARDSEL='.match,.match-card,.game,.game-card,.fixture,.fixture-card,.event-card,.spiel,.spiel-card,[data-match],[data-game],[data-fixture],.card,article,li,tr';
const TEAMSEL='.club,.team,.team-name,.club-name,.home-team,.away-team,.team-home,.team-away,[data-team],[data-home],[data-away]';
const TIME_RE=/\b(?:[01]?\d|2[0-3]):[0-5]\d\b/;
const SCORE_RE=/\b\d{1,2}\s*[:\-]\s*\d{1,2}\b/;
const PROVIDER_RE=/\b(DAZN|Sky|WOW|RTL\+?|ARD|ZDF|Prime(?: Video)?|Amazon|Magenta(?:TV| Sport)?|Sport1|OneFootball|YouTube|Joyn|ServusTV|SAT\.?1|ProSieben|Eurosport|DF1)\b/i;
const COMP_RE=/(Champions League|Europa League|Conference League|Bundesliga|2\. Bundesliga|3\. Liga|DFB.?Pokal|Premier League|La\s?Liga|Serie A|Ligue 1|Eredivisie|MLS|Club World Cup|Klub-WM|WM|EM|Nations League|Testspiel|Freundschaftsspiel)/i;
const HIGHLIGHT_RE=/\b(highlights?|zusammenfassung|video|tore|spielbericht|re-live|relive)\b/i;
const VIDEO_HOST_RE=/(youtube\.com|youtu\.be|dailymotion\.com|ardmediathek\.de|zdf\.de|sportschau\.de|sport1\.de|sky\.de|dazn\.com|rtl\.de|joyn\.de)/i;
const palette={"bayern munchen":["#d71920","#0066b2"],"borussia dortmund":["#f2d400","#111111","#111"],"rb leipzig":["#e30613","#ffffff","#111"],"vfb stuttgart":["#e32219","#ffffff","#111"],"bayer leverkusen":["#e32219","#151515"],"eintracht frankfurt":["#e1000f","#171717"],"1. fc koln":["#e30613","#ffffff","#111"],"1. fsv mainz 05":["#d71920","#ffffff","#111"],"werder bremen":["#008c4a","#ffffff","#111"],"sc freiburg":["#d71920","#111111"],"paris saint-germain":["#163b75","#d7182a"],"borussia m'gladbach":["#111111","#ffffff","#111"]};
const state={view:'today',search:'',competition:'all',matches:[],highlights:[],dateControls:[],dateIndex:0,engine:null,app:null,observer:null,refreshTimer:null,bootAt:Date.now(),loading:true,lastFingerprint:'',polls:0};
function colors(name){const k=norm(name);if(palette[k])return palette[k];let h=0;for(const c of k)h=(h*31+c.charCodeAt(0))%360;return[`hsl(${h} 68% 46%)`,`hsl(${(h+42)%360} 58% 27%)`]}
function initials(name){const p=(name||'').replace(/\b(fc|cf|sc|sv|fk|afc|club|de|the)\b/ig,'').trim().split(/\s+/).filter(Boolean);return(p.length>1?(p[0][0]||'')+(p[p.length-1][0]||''):(p[0]||'TV').slice(0,2)).toUpperCase()}
function markHTML(name){const[a,b,t]=colors(name);return`<span class="tvf-team-mark" style="--c1:${a};--c2:${b};${t?`--ct:${t};`:''}">${esc(initials(name))}</span>`}
function cleanTeam(s){return(s||'').replace(/^[★☆\s]+|[★☆\s]+$/g,'').replace(/\s+/g,' ').trim()}
function plausibleTeam(s){s=cleanTeam(s);if(!s||s.length<2||s.length>58)return false;if(TIME_RE.test(s)||SCORE_RE.test(s)||PROVIDER_RE.test(s)||COMP_RE.test(s))return false;if(/^(live|heute|morgen|beendet|pause|hz|anpfiff|stream|sender|free|kostenlos|details?|ticker|highlights?|video|vs\.?|gegen)$/i.test(s))return false;if(/^\d+$/.test(s))return false;return /[A-Za-zÀ-ž]/.test(s)}
function dataTeam(card,names){for(const name of names){const v=card.getAttribute?.('data-'+name)||card.dataset?.[name];if(plausibleTeam(v))return cleanTeam(v)}return''}
function uniqueTeams(card){const direct=[dataTeam(card,['home','homeTeam','team1']),dataTeam(card,['away','awayTeam','team2'])].filter(Boolean);if(direct.length===2&&norm(direct[0])!==norm(direct[1]))return direct;
 const out=[];for(const el of $$(card,TEAMSEL)){const t=cleanTeam(text(el));if(!plausibleTeam(t))continue;if(!out.some(x=>norm(x)===norm(t)))out.push(t);if(out.length===2)break}if(out.length===2)return out;
 const named=[];for(const el of $$(card,'[class*="team"],[class*="club"],[class*="home"],[class*="away"],strong,b,a,span')){if(el.children.length>2)continue;const t=cleanTeam(text(el));if(!plausibleTeam(t))continue;if(!named.some(x=>norm(x)===norm(t)))named.push(t);if(named.length===2)break}return named.slice(0,2)}
function competition(card){const e=$(card,'.competition,.comp,.league,.league-title,.competition-name,.tournament,.meta,[data-competition],[data-league]');let t=cleanTeam(e?.getAttribute?.('data-competition')||e?.getAttribute?.('data-league')||text(e));if(!t||t.length>90){const m=text(card).match(COMP_RE);t=m?.[1]||'Fußball'}return t.slice(0,90)}
function score(card){for(const e of $$(card,'.score,.result,.match-score,.kickoff,.kick,.ko,.time,.match-time,[data-time],[data-score]')){const t=text(e)||e.getAttribute?.('data-time')||e.getAttribute?.('data-score')||'';const sm=t.match(SCORE_RE);if(sm&&!TIME_RE.test(sm[0]))return{value:sm[0].replace(/\s*[-:]\s*/,' : '),isTime:false};const tm=t.match(TIME_RE);if(tm)return{value:tm[0],isTime:true}}
 const all=text(card);const tm=all.match(TIME_RE),sm=all.match(SCORE_RE);if(sm&&(!tm||sm.index!==tm.index))return{value:sm[0].replace(/\s*[-:]\s*/,' : '),isTime:false};return{value:tm?.[0]||'–',isTime:true}}
function isLive(card){const t=text(card).slice(0,260);return card.classList?.contains('live')||card.classList?.contains('tvf-is-live')||!!$(card,'.live,.live-badge,.live-status,[data-live="true"],[data-status="live"]')||/\bLIVE\b/i.test(t)||/\b\d{1,3}\s*['’]\b/.test(t)}
function minute(card){const m=text(card).match(/\b(\d{1,3})\s*['’]/);return m?m[1]+"'":''}
function providerFromText(t){const out=[];for(const m of t.matchAll(new RegExp(PROVIDER_RE.source,'ig'))){const v=m[1];if(!out.some(x=>norm(x.text)===norm(v)))out.push({text:v,href:'',free:/onefootball|ard|zdf|sport1|servustv/i.test(v)})}return out.slice(0,3)}
function providers(card){const area=$(card,'.channels,.broadcast,.foot,.providers,.stations,.sender,.streams')||card;const out=[];for(const e of $$(area,'.ch,.channel,.provider,.station,.stream-link,.sender,a')){const t=text(e);if(!t||t.length>44||HIGHLIGHT_RE.test(t)||/mehr|detail|weitere länder|facebook|instagram/i.test(t))continue;if(!PROVIDER_RE.test(t)&&e.tagName!=='A')continue;if(out.some(x=>norm(x.text)===norm(t)))continue;out.push({text:t,href:e.tagName==='A'?e.href:'',free:/free|kostenlos|onefootball|ard|zdf|sport1|servustv/i.test(t)});if(out.length===3)break}if(!out.length)return providerFromText(text(card));return out}
function ticker(card){const box=$(card,'.ticker,.live-ticker,.ticker-box,[data-ticker],.timeline,.match-events');if(!box)return[];return $$(box,'li,.ticker-row,.ticker-event,.event,.timeline-item').slice(-8).map(r=>text(r)).filter(Boolean)}
function isFavControl(el){return!!el&&(el.classList.contains('active')||el.classList.contains('on')||el.getAttribute('aria-pressed')==='true'||el.getAttribute('aria-checked')==='true'||el.checked===true)}
function favControls(card){return $$(card,'.favorite,.fav,.star,[data-fav],[data-favorite],[aria-label*="Favorit" i]').filter(e=>!e.closest('#tvf-app')).slice(0,2)}
function candidateScore(card,teams){const t=text(card);let s=0;if(teams.length===2)s+=5;if(TIME_RE.test(t)||SCORE_RE.test(t))s+=2;if(COMP_RE.test(t))s++;if(PROVIDER_RE.test(t))s++;if(isLive(card))s++;if(t.length>1500)s-=4;if(card.matches('.match,.match-card,.game,.game-card,.fixture,.fixture-card,.spiel,.spiel-card,[data-match],[data-game],[data-fixture]'))s+=3;return s}
function parseMatches(){const candidates=$$(state.engine,CARDSEL), best=new Map();for(const card of candidates){if(card.closest('#tvf-app'))continue;const teams=uniqueTeams(card);if(teams.length!==2)continue;const strength=candidateScore(card,teams);if(strength<6)continue;const sc=score(card), c=competition(card), base=teams.map(norm).join('|')+'|'+norm(c);const old=best.get(base);const weight=strength*10000-Math.min(text(card).length,9999);if(!old||weight>old.weight)best.set(base,{card,teams,sc,c,weight})}
 let id=0;const list=[];for(const v of best.values()){const favs=favControls(v.card);list.push({id:'m'+(++id),source:v.card,home:v.teams[0],away:v.teams[1],competition:v.c,score:v.sc.value,isTime:v.sc.isTime,live:isLive(v.card),minute:minute(v.card),providers:providers(v.card),ticker:ticker(v.card),favControls:favs,favHome:isFavControl(favs[0]),favAway:isFavControl(favs[1])})}state.matches=list;return list}
function urlFromControl(el){if(el.tagName==='A'&&el.href)return el.href;for(const a of ['data-href','data-url','href']){const v=el.getAttribute?.(a);if(v&&/^https?:/i.test(v))return v}const js=el.getAttribute?.('onclick')||'';const m=js.match(/https?:\/\/[^'"\s)]+/i);return m?.[0]||''}
function parseHighlights(){const seen=new Set,out=[];for(const el of $$(state.engine,'a,button,[data-url],[data-href]')){if(el.closest('#tvf-app'))continue;const label=text(el),url=urlFromControl(el);if(!HIGHLIGHT_RE.test(label)&&!VIDEO_HOST_RE.test(url))continue;if(!url&&el.tagName!=='BUTTON')continue;const near=el.closest('.match,.match-card,.game,.game-card,.fixture,.fixture-card,.spiel,.spiel-card,.card,article,li,tr')||el.parentElement;const teams=near?uniqueTeams(near):[];let title='';if(teams.length===2)title=teams[0]+' – '+teams[1];if(!title){const h=near&&$(near,'h1,h2,h3,h4,strong,.title,.headline');title=text(h)||label||'Highlight'}const desc=near?text($(near,'p,.desc,.description,.subtitle')):'';const key=(url||label)+'|'+title;if(seen.has(key))continue;seen.add(key);out.push({title:title.slice(0,120),label:(label||'Highlight ansehen').slice(0,60),url,desc:desc.slice(0,220)});if(out.length>=12)break}
 state.highlights=out;return out}
function collectDates(){const sels='.datebar button,.date-nav button,.dates button,.m-datebar button,.datebar a,.date-nav a,.dates a,.m-datebar a,[data-date]';const unique=[];for(const e of $$(state.engine,sels)){if(e.closest('#tvf-app'))continue;const t=text(e);if(!t||t.length>40)continue;if(!unique.includes(e))unique.push(e);if(unique.length===7)break}state.dateControls=unique}
function cloneBrand(){const old=$(state.engine,'header .logo,.hdr .logo')||$(state.engine,'header a,.hdr a');if(old){const c=old.cloneNode(true);c.querySelectorAll('script').forEach(x=>x.remove());return c.outerHTML}return'<div class="tvf-brand-text"><span class="tvf-brand-box">TV</span>FUSSBALL.de</div>'}
function buildApp(){const root=document.createElement('div');root.id='tvf-app';root.className='tvf-app';root.innerHTML=`<header class="tvf-app-header"><div class="tvf-brand">${cloneBrand()}</div><nav class="tvf-topnav"><button class="active" data-view="today">Heute</button><button data-view="live">Live</button><button data-view="mine">Meine <span class="tvf-count">0</span></button><button data-view="highlights">Highlights</button></nav><div class="tvf-header-actions"><label class="tvf-search"><input type="search" placeholder="Suche (Team, Wettbewerb, Sender)" aria-label="Suche"></label><button class="tvf-theme" type="button" aria-label="Darstellung">☾</button></div></header><section class="tvf-hero"><div class="tvf-wrap"><div class="tvf-hero-copy"><div class="tvf-eyebrow">Fußball im TV & Stream</div><h1>Kein Spiel<br>mehr verpassen.</h1><p>Alle wichtigen Fußballspiele, Sender und Live-Updates auf einen Blick.</p><div class="tvf-stats"><div class="tvf-stat"><span class="tvf-stat-icon">⚽</span><div><strong data-stat="games">0</strong><span>Spiele heute</span></div></div><div class="tvf-stat"><span class="tvf-stat-icon">◉</span><div><strong data-stat="live">0</strong><span>Live</span></div></div><div class="tvf-stat"><span class="tvf-stat-icon">☆</span><div><strong data-stat="fav">0</strong><span>Favoriten</span></div></div></div></div><div class="tvf-datebar"></div><div class="tvf-chips"></div></div></section><main class="tvf-main"><div class="tvf-results"></div></main><nav class="tvf-mobile-nav"><button class="active" data-view="today">Heute</button><button data-view="live">Live</button><button data-view="mine">★ Meine</button><button data-view="highlights">Highlights</button></nav>`;document.body.insertBefore(root,state.engine);state.app=root;bindApp()}
function bindApp(){state.app.addEventListener('click',e=>{const view=e.target.closest('[data-view]');if(view){setView(view.dataset.view);return}const chip=e.target.closest('[data-comp]');if(chip){state.competition=chip.dataset.comp;render();return}const fav=e.target.closest('[data-fav-match]');if(fav){const m=state.matches.find(x=>x.id===fav.dataset.favMatch),idx=Number(fav.dataset.team||0),ctl=m?.favControls?.[idx];if(ctl){ctl.click();setTimeout(refresh,150)}return}const all=e.target.closest('[data-show-all]');if(all){setView(all.dataset.showAll);return}const more=e.target.closest('.tvf-chip.more');if(more){state.app.classList.toggle('tvf-show-all-chips');renderChips(true)}});const input=$(state.app,'.tvf-search input');input.addEventListener('input',()=>{state.search=input.value;render()});$(state.app,'.tvf-theme').addEventListener('click',()=>state.app.classList.toggle('tvf-low-contrast'))}
function setView(view){state.view=view;state.competition='all';$$(state.app,'[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render()}
function filtered(){let list=[...state.matches];if(state.view==='live')list=list.filter(m=>m.live);if(state.view==='mine')list=list.filter(m=>m.favHome||m.favAway);if(state.competition!=='all')list=list.filter(m=>norm(m.competition).includes(state.competition));const s=norm(state.search);if(s)list=list.filter(m=>norm([m.home,m.away,m.competition,...m.providers.map(p=>p.text)].join(' ')).includes(s));return list}
function teamHTML(name,m,idx){const active=idx===0?m.favHome:m.favAway;return`<div class="tvf-team">${markHTML(name)}<div class="tvf-team-name">${esc(name)} <button class="tvf-team-fav ${active?'active':''}" data-fav-match="${m.id}" data-team="${idx}" title="${active?'Favorit entfernen':'Als Favorit markieren'}">★</button></div></div>`}
function providerHTML(p){const tag=p.href?'a':'span';return`<${tag} class="tvf-provider ${p.free?'free':''}" ${p.href?`href="${esc(p.href)}" target="_blank" rel="noopener"`:''}>${esc(p.text)}</${tag}>`}
function liveCard(m){return`<article class="tvf-live-card"><div class="tvf-card-meta"><span class="tvf-live-badge">LIVE</span><span class="tvf-minute">${esc(m.minute||'LIVE')}</span></div><div class="tvf-card-match">${teamHTML(m.home,m,0)}<div class="tvf-score">${esc(m.score)}</div>${teamHTML(m.away,m,1)}</div><div class="tvf-card-foot">${m.providers.map(providerHTML).join('')}</div>${m.ticker.length?`<div class="tvf-ticker">${m.ticker.map(t=>`<div class="tvf-ticker-event">${esc(t)}</div>`).join('')}</div>`:''}</article>`}
function laterRow(m){return`<article class="tvf-later-row"><div class="tvf-later-time">${esc(m.score)}</div><div class="tvf-later-team">${markHTML(m.home)}<div class="tvf-team-name">${esc(m.home)} <button class="tvf-team-fav ${m.favHome?'active':''}" data-fav-match="${m.id}" data-team="0">★</button></div></div><div class="tvf-vs">vs.</div><div class="tvf-later-team">${markHTML(m.away)}<div class="tvf-team-name">${esc(m.away)} <button class="tvf-team-fav ${m.favAway?'active':''}" data-fav-match="${m.id}" data-team="1">★</button></div></div><div class="tvf-later-providers">${m.providers.map(providerHTML).join('')}</div></article>`}
function sectionHead(type,count){return`<div class="tvf-section-head ${type==='live'?'live':''}"><div class="tvf-section-title"><h2>${type==='live'?'Jetzt live':'Später heute'} <span>(${count})</span></h2></div><button data-show-all="${type==='live'?'live':'today'}">${type==='live'?'Alle Live-Spiele anzeigen':'Alle Spiele von heute anzeigen'} ›</button></div>`}
function renderHighlights(){const cards=state.highlights.map(h=>`<article class="tvf-highlight"><h3>${esc(h.title)}</h3>${h.desc?`<p>${esc(h.desc)}</p>`:''}${h.url?`<a class="tvf-highlight-link" href="${esc(h.url)}" target="_blank" rel="noopener">${esc(h.label||'Highlight ansehen')} ›</a>`:`<span class="tvf-highlight-link">${esc(h.label)}</span>`}</article>`).join('');const empty=state.loading?'<div class="tvf-empty">Highlights werden geladen …</div>':'<div class="tvf-empty">Aktuell sind keine Highlights verfügbar.</div>';return`<div class="tvf-section-head"><div class="tvf-section-title"><h2>Highlights <span>(${state.highlights.length})</span></h2></div></div><div class="tvf-highlights">${cards||empty}</div>`}
function render(){if(!state.app)return;renderDates();renderChips();const result=$(state.app,'.tvf-results');if(state.view==='highlights'){result.innerHTML=renderHighlights();updateStats();return}const list=filtered(),lives=list.filter(m=>m.live),later=list.filter(m=>!m.live);let html='';if(state.view!=='live'&&lives.length)html+=sectionHead('live',lives.length)+`<div class="tvf-live-grid">${lives.map(liveCard).join('')}</div>`;else if(state.view==='live'&&lives.length)html+=sectionHead('live',lives.length)+`<div class="tvf-live-grid">${lives.map(liveCard).join('')}</div>`;if(state.view!=='live'&&later.length)html+=sectionHead('later',later.length)+`<div class="tvf-later-list">${later.map(laterRow).join('')}</div>`;if(!list.length)html=state.loading?'<div class="tvf-empty">Spielplan wird geladen …</div>':'<div class="tvf-empty">Keine passenden Spiele gefunden.</div>';result.innerHTML=html;updateStats()}
function renderDates(){const bar=$(state.app,'.tvf-datebar');if(!bar)return;const fallback=['Heute','Mi.','Do.','Fr.','Sa.','So.','Mo.'];const labels=state.dateControls.length?state.dateControls.map(x=>text(x)):fallback;bar.innerHTML=labels.slice(0,7).map((label,i)=>{const parts=label.split(/\s+/);return`<button class="tvf-date ${i===state.dateIndex?'active':''}" data-date-index="${i}">${esc(parts[0]||fallback[i])}<small>${esc(parts.slice(1).join(' '))}</small></button>`}).join('')+'<div class="tvf-calendar">▣</div>';$$ (bar,'[data-date-index]').forEach(b=>b.addEventListener('click',()=>switchDate(Number(b.dataset.dateIndex))))}
function switchDate(i){state.dateIndex=i;const ctl=state.dateControls[i];if(ctl){try{ctl.click()}catch{}state.loading=true;render();setTimeout(refresh,250);setTimeout(refresh,900)}else render()}
function renderChips(forceAll=false){const box=$(state.app,'.tvf-chips');if(!box)return;const comps=[...new Set(state.matches.map(m=>m.competition).filter(Boolean))];const expanded=forceAll||state.app.classList.contains('tvf-show-all-chips');const shown=expanded?comps:comps.slice(0,5);box.innerHTML=`<button class="tvf-chip ${state.competition==='all'?'active':''}" data-comp="all">Alle Wettbewerbe　⌄</button>${shown.map((c,i)=>`<button class="tvf-chip ${i<2?'star':'plus'} ${state.competition===norm(c)?'active':''}" data-comp="${esc(norm(c))}">${esc(c)}</button>`).join('')}${comps.length>5?`<button class="tvf-chip more" type="button">☷　${expanded?'Weniger':'Mehr Filter'}</button>`:''}`}
function updateStats(){const favTeams=new Set;for(const m of state.matches){if(m.favHome)favTeams.add(norm(m.home));if(m.favAway)favTeams.add(norm(m.away))}const set=(k,v)=>{const e=$(state.app,`[data-stat="${k}"]`);if(e)e.textContent=v};set('games',state.matches.length);set('live',state.matches.filter(m=>m.live).length);set('fav',favTeams.size);$$(state.app,'.tvf-count').forEach(e=>e.textContent=favTeams.size)}
function fingerprint(){return state.matches.map(m=>[m.home,m.away,m.score,m.live,m.providers.map(p=>p.text).join(',')].join('|')).join('||')+'##'+state.highlights.map(h=>h.url+h.title).join('|')}
function refresh(){parseMatches();parseHighlights();collectDates();state.polls++;if(state.matches.length||Date.now()-state.bootAt>20000)state.loading=false;const fp=fingerprint();if(fp!==state.lastFingerprint||state.polls<4||!state.loading){state.lastFingerprint=fp;render()}}
function makeEngine(){const engine=document.createElement('div');engine.className='tvf-engine';engine.setAttribute('aria-hidden','true');const script=document.currentScript;const nodes=[...document.body.childNodes].filter(n=>n!==script);for(const n of nodes)engine.appendChild(n);document.body.appendChild(engine);state.engine=engine}
function observe(){state.observer=new MutationObserver(mutations=>{if(!mutations.some(m=>!m.target.closest?.('#tvf-app')) )return;clearTimeout(state.refreshTimer);state.refreshTimer=setTimeout(refresh,140)});state.observer.observe(state.engine,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['class','aria-pressed','aria-checked','data-live','data-status','href']})}
function poll(){let n=0;const times=[250,600,1100,1800,2800,4200,6500,9000,12500,16000,20500];for(const ms of times)setTimeout(()=>{refresh();n++;},ms)}
function boot(){makeEngine();collectDates();parseMatches();parseHighlights();buildApp();render();observe();poll()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();