(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const norm=v=>String(v??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
const initials=name=>String(name||'TV').replace(/\b(fc|cf|sc|sv|fk|afc|club|de|the)\b/ig,'').trim().split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()||'TV';
const getKey=day=>{const m=String(day||'').match(/(\d{1,2})\.(\d{1,2})\.(\d{4})/);return m?Number(m[3])*10000+Number(m[2])*100+Number(m[1]):0};
const todayKey=()=>{try{if(typeof TODAY_KEY!=='undefined'&&TODAY_KEY)return Number(TODAY_KEY)}catch(e){}const d=new Date();return d.getFullYear()*10000+(d.getMonth()+1)*100+d.getDate()};
const dayShort=day=>{const m=String(day||'').match(/(?:([^,]+),\s*)?(\d{1,2})\.(\d{1,2})\.(\d{4})/);if(!m)return day||'';const k=Number(m[4])*10000+Number(m[3])*100+Number(m[2]);const diff=Math.round((new Date(Number(m[4]),Number(m[3])-1,Number(m[2]))-new Date(new Date().getFullYear(),new Date().getMonth(),new Date().getDate()))/86400000);if(diff===0)return'Heute · '+m[2]+'.'+m[3]+'.';if(diff===1)return'Morgen · '+m[2]+'.'+m[3]+'.';return (m[1]?m[1].slice(0,2)+'. · ':'')+m[2]+'.'+m[3]+'.'};
function sourceData(){let matches=[],highlights=[],sources={},market='DE';try{if(typeof MATCHES!=='undefined'&&Array.isArray(MATCHES))matches=MATCHES}catch(e){}try{if(typeof HL!=='undefined'&&Array.isArray(HL))highlights=HL}catch(e){}try{if(typeof HL_SRC!=='undefined'&&HL_SRC)sources=HL_SRC}catch(e){}try{if(typeof COUNTRY!=='undefined'&&COUNTRY)market=COUNTRY}catch(e){}return{matches,highlights,sources,market}}
function providers(m,market){const tv=m&&m.tv||{};let list=tv[market]||tv.DE||[];if(!Array.isArray(list))list=[list].filter(Boolean);return list.filter(Boolean).map(p=>typeof p==='string'?{n:p,t:'',q:'',u:''}:p).filter(p=>p&&p.n)}
function moveLegacy(){const body=document.body,cur=document.currentScript,engine=document.createElement('div');engine.id='tvf-source-engine';const kids=[...body.children];for(const el of kids){if(el!==cur)engine.appendChild(el)}body.insertBefore(engine,cur);return engine}
function matchCard(m,market){const ps=providers(m,market);const channel=ps.length?ps.map(p=>{const cls=p.t==='fta'?'tvfd-provider free':'tvfd-provider';const inside=`<i class="tvfd-dot"></i>${esc(p.n)}${p.q?` · ${esc(p.q)}`:''}`;return p.u?`<a class="${cls}" href="${esc(p.u)}" target="_blank" rel="noopener">${inside}</a>`:`<span class="${cls}">${inside}</span>`}).join(''):'<span class="tvfd-provider">Sender noch offen</span>';
 return `<article class="tvfd-card" data-search="${esc(norm([m.h,m.a,m.comp,ps.map(p=>p.n).join(' ')].join(' ')))}" data-comp="${esc(m.comp||'Fußball')}"><div class="tvfd-cardtop"><span class="tvfd-comp">${esc(m.comp||'Fußball')}</span><span class="tvfd-time">${esc(m.time||'–')}</span></div><div class="tvfd-teams"><div class="tvfd-team"><span class="tvfd-ball">${esc(initials(m.h))}</span><span>${esc(m.h||'Heim')}</span></div><div class="tvfd-team"><span class="tvfd-ball">${esc(initials(m.a))}</span><span>${esc(m.a||'Auswärts')}</span></div></div><div class="tvfd-providers">${channel}</div></article>`}
function sourceLinks(h,sources){const out=[];const add=(label,url)=>{if(!url||typeof url!=='string'||!/^https?:/i.test(url)||out.some(x=>x.url===url))return;out.push({label:label||'Highlight',url})};if(typeof h.zdf==='string')add('ZDF',h.zdf);if(typeof h.full==='string')add('Video',h.full);const keys=[`${h.h}|${h.a}`,`${h.a}|${h.h}`];for(const key of keys){const list=sources&&sources[key];if(!Array.isArray(list))continue;for(const item of list){if(Array.isArray(item))add(item[1]||item[0],item[2]);else if(item&&typeof item==='object')add(item.label||item.name,item.url||item.href)}}return out.slice(0,3)}
function highlightCard(h,sources){const links=sourceLinks(h,sources);const analyse=h&&h.analyse||{};const fazit=analyse.fazit&&(analyse.fazit.de||analyse.fazit.en)||'';const note=analyse.spielnote&&analyse.spielnote.wert;return `<article class="tvfd-card tvfd-hl" data-search="${esc(norm([h.h,h.a,h.g,h.date].join(' ')))}"><div class="tvfd-cardtop" style="margin:-16px -16px 14px"><span class="tvfd-comp">${esc(h.g||'Highlight')}</span><span class="tvfd-time">${esc(h.date||'')}</span></div><div class="tvfd-hlteams">${esc(h.h||'')} – ${esc(h.a||'')}</div><div class="tvfd-hlscore">${esc(h.s||'–')}</div>${note?`<div class="tvfd-note">★ Spielnote ${esc(note)}</div>`:''}${fazit?`<p class="tvfd-hltext">${esc(fazit)}</p>`:''}${links.length?`<div class="tvfd-links">${links.map(l=>`<a class="tvfd-link" href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.label)}</a>`).join('')}</div>`:''}</article>`}
function shell(isHighlights){const root=document.createElement('div');root.id='tvf-direct-app';root.innerHTML=`<header class="tvfd-head"><div class="tvfd-wrap tvfd-headin"><a class="tvfd-brand" href="index.html"><b>TV</b>FUSSBALL.de</a><nav class="tvfd-nav"><a href="index.html" class="${isHighlights?'':'active'}">Heute</a><a href="highlights.html" class="${isHighlights?'active':''}">Highlights</a><a href="anbieter.html">Anbieter</a></nav></div></header><section class="tvfd-hero"><div class="tvfd-wrap"><div class="tvfd-kicker">${isHighlights?'Tore · Zusammenfassungen · Analysen':'Fußball im TV & Stream'}</div><h1 class="tvfd-title">${isHighlights?'Die Spiele. Die Tore.':'Kein Spiel mehr verpassen.'}</h1><p class="tvfd-lead">${isHighlights?'Aktuelle Highlights und Spielzusammenfassungen direkt aus dem gepflegten TVFussball-Datensatz.':'Aktuelle Spiele, Anstoßzeiten und Sender – direkt aus dem gepflegten TVFussball-Spielplan.'}</p><div class="tvfd-stats"><div class="tvfd-stat"><strong data-stat="count">0</strong><span>${isHighlights?'Highlights':'Spiele'}</span></div><div class="tvfd-stat"><strong data-stat="free">0</strong><span>${isHighlights?'mit Video-Link':'mit Free-TV'}</span></div></div></div></section><section class="tvfd-controls"><div class="tvfd-wrap"><div class="tvfd-daytabs"></div><div class="tvfd-tools"><input class="tvfd-search" type="search" placeholder="${isHighlights?'Teams oder Wettbewerb suchen':'Team, Wettbewerb oder Sender suchen'}" aria-label="Suche"><select class="tvfd-select" aria-label="Wettbewerb"><option value="all">Alle Wettbewerbe</option></select></div></div></section><main class="tvfd-main"><div class="tvfd-wrap"><div class="tvfd-sectionhead"><h2 data-title>${isHighlights?'Neueste Highlights':'Spiele'}</h2><span data-sub></span></div><div class="tvfd-grid" data-grid></div></div></main><footer class="tvfd-footer"><div class="tvfd-wrap tvfd-footerin"><span>TVFussball.de · Daten direkt aus der gepflegten HTML-Quelle</span><span><a href="impressum.html">Impressum</a> · <a href="datenschutz.html">Datenschutz</a></span></div></footer>`;document.body.insertBefore(root,document.currentScript);return root}
function init(){const data=sourceData(),isHighlights=/highlights\.html$/i.test(location.pathname),engine=moveLegacy(),root=shell(isHighlights);const grid=root.querySelector('[data-grid]'),search=root.querySelector('.tvfd-search'),select=root.querySelector('.tvfd-select'),tabs=root.querySelector('.tvfd-daytabs'),title=root.querySelector('[data-title]'),sub=root.querySelector('[data-sub]');let selectedDay=0;
 if(isHighlights){const hs=data.highlights||[];const comps=[...new Set(hs.map(h=>h.g).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'de')).slice(0,80);for(const c of comps)select.insertAdjacentHTML('beforeend',`<option value="${esc(c)}">${esc(c)}</option>`);tabs.style.display='none';function render(){const q=norm(search.value),comp=select.value;const filtered=hs.filter(h=>(comp==='all'||h.g===comp)&&(!q||norm([h.h,h.a,h.g,h.date].join(' ')).includes(q))).slice(0,80);grid.innerHTML=filtered.length?filtered.map(h=>highlightCard(h,data.sources)).join(''):'<div class="tvfd-empty"><strong>Keine Highlights gefunden</strong>Versuche einen anderen Suchbegriff.</div>';root.querySelector('[data-stat="count"]').textContent=String(hs.length);root.querySelector('[data-stat="free"]').textContent=String(hs.filter(h=>sourceLinks(h,data.sources).length).length);sub.textContent=`${filtered.length} angezeigt`};search.addEventListener('input',render);select.addEventListener('change',render);render();}
 else{const tk=todayKey();const future=data.matches.filter(m=>getKey(m.day)>=tk).sort((a,b)=>getKey(a.day)-getKey(b.day)||String(a.time).localeCompare(String(b.time)));const days=[...new Map(future.map(m=>[getKey(m.day),m.day])).entries()].sort((a,b)=>a[0]-b[0]);selectedDay=days.some(d=>d[0]===tk)?tk:(days[0]?.[0]||tk);const comps=[...new Set(future.map(m=>m.comp).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'de')).slice(0,100);for(const c of comps)select.insertAdjacentHTML('beforeend',`<option value="${esc(c)}">${esc(c)}</option>`);tabs.innerHTML=days.slice(0,9).map(([k,d])=>`<button class="tvfd-day${k===selectedDay?' active':''}" data-day="${k}">${esc(dayShort(d))}</button>`).join('');function render(){const q=norm(search.value),comp=select.value;const dayMatches=future.filter(m=>getKey(m.day)===selectedDay);const filtered=dayMatches.filter(m=>(comp==='all'||m.comp===comp)&&(!q||norm([m.h,m.a,m.comp,providers(m,data.market).map(p=>p.n).join(' ')].join(' ')).includes(q)));grid.innerHTML=filtered.length?filtered.map(m=>matchCard(m,data.market)).join(''):'<div class="tvfd-empty"><strong>Keine Spiele für diese Auswahl</strong>Für diesen Tag sind im aktuellen Datensatz keine passenden Spiele hinterlegt.</div>';const dayName=days.find(d=>d[0]===selectedDay)?.[1]||'';title.textContent=dayShort(dayName)||'Spiele';sub.textContent=`${filtered.length} Spiele · Markt ${esc(data.market)}`;root.querySelector('[data-stat="count"]').textContent=String(dayMatches.length);root.querySelector('[data-stat="free"]').textContent=String(dayMatches.filter(m=>providers(m,data.market).some(p=>p.t==='fta')).length)}tabs.addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(!b)return;selectedDay=Number(b.dataset.day);tabs.querySelectorAll('.tvfd-day').forEach(x=>x.classList.toggle('active',x===b));render()});search.addEventListener('input',render);select.addEventListener('change',render);render()}
 document.documentElement.classList.remove('tvf-direct-boot');document.documentElement.classList.add('tvf-direct-ready');setTimeout(()=>{engine.setAttribute('aria-hidden','true')},0)}
try{if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()}catch(err){console.error('[TVF Direct]',err);document.documentElement.classList.remove('tvf-direct-boot');document.documentElement.classList.add('tvf-direct-ready')}
})();